### ISSUE TITLE
Cleartext password

### ISSUE THREAD

**Issue by PabloCamp0s** [paduel/darwinex_ticks#1]
Hi.

I'm not sure, but I think that your current README.md contains an example for command line usage with a cleartext password.

This is a warning just in case.

Great effort anyway. Best regards.

**Comment by Python-Trading** [comment]
Thanks for your warning!  Obviously is not my real password ;D  Only a fake example.

**Comment by PabloCamp0s** [comment]
I thought so. However, it's more common to see stuff like *[password]* or
so in such examples. This is the reason behind my "just in case" warning.

**Comment by paduel** [comment]
Thanks for your warning!  Obviously is not my real password ;D  Only a fake example.

Thank you
