### ISSUE TITLE
TypeError: concat() got an unexpected keyword argument 'sort'

### ISSUE THREAD

**Issue by rrampaer** [paduel/darwinex_ticks#2]
https://github.com/paduel/darwinex_ticks/blob/a27966510d30c44cdfa8f8c4a7bddb6fa7e16be5/darwinex_ticks/core.py#L171  

Removing the sort arg in concat solves the issue, does that affect your function's way of working?

**Comment by Python-Trading** [comment]
Please, what Python and Pandas version are you using?

**Comment by rrampaer** [comment]
> Please, what Python and Pandas version are you using?

Python 3.5.1 / pandas 0.21.0

**Comment by paduel** [comment]
Upgrade to Pandas 23 or upper to avoid the error.

I will update requirements.txt at next version. Thank for the issue.
